# @package _global_.model
model_type: dream-7b
hf_model_name: Dream-org/Dream-v0-Instruct-7B
model_base_path: ${oc.env:MODELS,null}
device_map: auto
torch_dtype: bfloat16
trust_remote_code: true
cache_dir: null
