# @package _global_.model
model_type: llada-8b-base
hf_model_name: GSAI-ML/LLaDA-8B-Base
model_base_path: ${oc.env:MODELS,null}
device_map: auto
torch_dtype: bfloat16
trust_remote_code: true
cache_dir: null
