# @package _global_.model
model_type: qwen-2.5-7b-base
hf_model_name: Qwen/Qwen2.5-7B
model_base_path: ${oc.env:MODELS,null}
device_map: auto
torch_dtype: bfloat16
trust_remote_code: true
cache_dir: null
